# Generated by Django 4.1.5 on 2023-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(default='', max_length=500)),
                ('url_hash', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
